import type { Artwork } from "@atelier/contracts";
import { landscapeImage, portraitImage, squareImage } from "./images";

export const artworks: Artwork[] = [
  {
    id: "aw-01-morning-tide",
    title: "Morning Tide",
    artistId: "artist-lena-moreau",
    artist: "Lena Moreau",
    price: 1280,
    currency: "USD",
    widthCm: 90,
    heightCm: 110,
    medium: "Oil and wax on canvas",
    style: ["Abstract", "Organic"],
    dominantColors: ["Ivory", "Warm Grey", "Sand"],
    editionType: "original",
    availability: "available",
    verificationStatus: "verified",
    imageUrl: portraitImage("art-01"),
    orientation: "portrait",
    year: 2024,
    coaUrl: "https://picsum.photos/seed/coa-01/800/1000",
  },
  {
    id: "aw-02-ember-field",
    title: "Ember Field",
    artistId: "artist-lena-moreau",
    artist: "Lena Moreau",
    price: 960,
    currency: "USD",
    widthCm: 120,
    heightCm: 90,
    medium: "Oil on canvas",
    style: ["Abstract", "Gestural"],
    dominantColors: ["Terracotta", "Charcoal", "Ochre"],
    editionType: "original",
    availability: "available",
    verificationStatus: "verified",
    imageUrl: landscapeImage("art-02"),
    orientation: "landscape",
    year: 2023,
  },
  {
    id: "aw-03-linen-room",
    title: "Linen Room",
    artistId: "artist-ivan-petrova",
    artist: "Ivan Petrov",
    price: 720,
    currency: "USD",
    widthCm: 70,
    heightCm: 90,
    medium: "Oil on linen",
    style: ["Figurative", "Interior"],
    dominantColors: ["Linen", "Clay", "Sage"],
    editionType: "original",
    availability: "available",
    verificationStatus: "verified",
    imageUrl: portraitImage("art-03"),
    orientation: "portrait",
    year: 2024,
  },
  {
    id: "aw-04-silent-hall",
    title: "Silent Hall",
    artistId: "artist-ivan-petrova",
    artist: "Ivan Petrov",
    price: 890,
    currency: "USD",
    widthCm: 100,
    heightCm: 80,
    medium: "Oil on linen",
    style: ["Figurative", "Interior"],
    dominantColors: ["Dove Grey", "Bone", "Umber"],
    editionType: "original",
    availability: "reserved",
    verificationStatus: "verified",
    imageUrl: landscapeImage("art-04"),
    orientation: "landscape",
    year: 2023,
  },
  {
    id: "aw-05-infinite-courtyard",
    title: "Infinite Courtyard",
    artistId: "artist-aki-tanaka",
    artist: "Aki Tanaka",
    price: 1580,
    currency: "USD",
    widthCm: 100,
    heightCm: 100,
    medium: "Mineral pigment on washi",
    style: ["Abstract", "Minimal"],
    dominantColors: ["Ink", "Stone", "Pale Moss"],
    editionType: "original",
    availability: "available",
    verificationStatus: "verified",
    imageUrl: squareImage("art-05"),
    orientation: "square",
    year: 2024,
  },
  {
    id: "aw-06-vermilion-study",
    title: "Vermilion Study",
    artistId: "artist-aki-tanaka",
    artist: "Aki Tanaka",
    price: 640,
    currency: "USD",
    widthCm: 60,
    heightCm: 80,
    medium: "Mineral pigment on paper",
    style: ["Abstract", "Minimal"],
    dominantColors: ["Vermilion", "Bone", "Charcoal"],
    editionType: "limited-edition",
    availability: "available",
    verificationStatus: "verified",
    imageUrl: portraitImage("art-06"),
    orientation: "portrait",
    year: 2024,
  },
  {
    id: "aw-07-concrete-light",
    title: "Concrete Light",
    artistId: "artist-maria-wood",
    artist: "Maria Wood",
    price: 540,
    currency: "USD",
    widthCm: 80,
    heightCm: 60,
    medium: "Archival pigment print",
    style: ["Photography", "Architecture"],
    dominantColors: ["Grey", "Concrete", "Sky"],
    editionType: "limited-edition",
    availability: "available",
    verificationStatus: "pending",
    imageUrl: landscapeImage("art-07"),
    orientation: "landscape",
    year: 2023,
  },
  {
    id: "aw-08-below-the-freeway",
    title: "Below the Freeway",
    artistId: "artist-maria-wood",
    artist: "Maria Wood",
    price: 610,
    currency: "USD",
    widthCm: 100,
    heightCm: 100,
    medium: "Archival pigment print",
    style: ["Photography", "Architecture"],
    dominantColors: ["Charcoal", "Cement", "Amber"],
    editionType: "limited-edition",
    availability: "sold",
    verificationStatus: "pending",
    imageUrl: squareImage("art-08"),
    orientation: "square",
    year: 2023,
  },
  {
    id: "aw-09-song-for-the-floor",
    title: "Song for the Floor",
    artistId: "artist-old-rakim",
    artist: "Elias Rahim",
    price: 2100,
    currency: "USD",
    widthCm: 150,
    heightCm: 110,
    medium: "Acrylic on canvas",
    style: ["Abstract", "Gestural"],
    dominantColors: ["Oxblood", "Cream", "Ink"],
    editionType: "original",
    availability: "available",
    verificationStatus: "verified",
    imageUrl: landscapeImage("art-09"),
    orientation: "landscape",
    year: 2024,
  },
  {
    id: "aw-10-blue-architecture",
    title: "Blue Architecture",
    artistId: "artist-old-rakim",
    artist: "Elias Rahim",
    price: 1380,
    currency: "USD",
    widthCm: 90,
    heightCm: 120,
    medium: "Acrylic on canvas",
    style: ["Abstract", "Geometric"],
    dominantColors: ["Indigo", "Oxblood", "Stone"],
    editionType: "original",
    availability: "available",
    verificationStatus: "verified",
    imageUrl: portraitImage("art-10"),
    orientation: "portrait",
    year: 2023,
  },
  {
    id: "aw-11-north-field",
    title: "North Field",
    artistId: "artist-sara-lindqvist",
    artist: "Sara Lindqvist",
    price: 790,
    currency: "USD",
    widthCm: 110,
    heightCm: 90,
    medium: "Oil on canvas",
    style: ["Landscape", "Minimal"],
    dominantColors: ["Grey", "Mist", "Slate"],
    editionType: "original",
    availability: "available",
    verificationStatus: "pending",
    imageUrl: landscapeImage("art-11"),
    orientation: "landscape",
    year: 2024,
  },
  {
    id: "aw-12-first-snow",
    title: "First Snow",
    artistId: "artist-sara-lindqvist",
    artist: "Sara Lindqvist",
    price: 470,
    currency: "USD",
    widthCm: 60,
    heightCm: 76,
    medium: "Oil on canvas",
    style: ["Landscape", "Minimal"],
    dominantColors: ["White", "Silver", "Grey"],
    editionType: "limited-edition",
    availability: "sold",
    verificationStatus: "pending",
    imageUrl: portraitImage("art-12"),
    orientation: "portrait",
    year: 2024,
  },
];
